# Generated by Django 3.2.9 on 2021-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=-4882, help_text='Номер телефона', max_length=100),
            preserve_default=False,
        ),
    ]
