# Generated by Django 3.2.9 on 2021-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_remove_inquiry_inquiry_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_auto_invisible_date',
            field=models.DateTimeField(blank=True, help_text='Дата актуальности', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_category',
            field=models.CharField(choices=[('0', 'Купля/продажа'), ('1', 'Аренда'), ('2', 'Ремонтные работы'), ('3', 'Отключение услуг'), ('4', 'Placeholder'), ('5', 'Placeholder')], default='0', help_text='Категория объявления', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_deadline',
            field=models.DateTimeField(help_text='Дата завершения голосования'),
        ),
    ]
