# Generated by Django 3.2.9 on 2021-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_auto_20211226_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_auto_invisible_date',
            field=models.DateField(blank=True, help_text='Дата актуальности', null=True),
        ),
    ]
