# Generated by Django 3.2.9 on 2022-01-03 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_announcement_announcement_auto_invisible_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время комментария'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата обновления заявки'),
            preserve_default=False,
        ),
    ]
